DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Employer;

CREATE TABLE [Client] (
  [ClientID] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY ON CONFLICT FAIL, 
  [EmployeeID] INTEGER NOT NULL ON CONFLICT FAIL CONSTRAINT [Worker] REFERENCES [Employee]([ID]) ON DELETE CASCADE ON UPDATE CASCADE, 
  [ClientName] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [Address] VARCHAR(100) NOT NULL ON CONFLICT FAIL, 
  [City] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [State] CHAR(2) NOT NULL ON CONFLICT FAIL);

CREATE TABLE [Employee] (
  [ID] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY CONSTRAINT [Employer] REFERENCES [Employer]([EmployerID]) ON DELETE CASCADE ON UPDATE CASCADE, 
  [EmployerID] INTEGER NOT NULL ON CONFLICT FAIL, 
  [FirstName] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [LastName] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [Address] VARCHAR(100) NOT NULL ON CONFLICT FAIL, 
  [City] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [State] CHAR(2) NOT NULL ON CONFLICT FAIL);

CREATE TABLE [Employer] (
  [EmployerID] INTEGER PRIMARY KEY NOT NULL ON CONFLICT FAIL, 
  [CompanyName] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [Address] VARCHAR(100) NOT NULL ON CONFLICT FAIL, 
  [City] VARCHAR(50) NOT NULL ON CONFLICT FAIL, 
  [State] CHAR(2) NOT NULL ON CONFLICT FAIL);